jobs:
  generate-changelog:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: BobAnkh/auto-generate-changelog@v1.2.5
      with:
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PATH: CHANGELOG.md
        TYPE: feat:Feature,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance
          Improvements
name: Generate changelog
on:
  repository_dispatch:
    types: trigger-ga___changelog.yml
