env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
jobs:
  dependency-review:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Dependency Review
      uses: actions/dependency-review-action@v4
name: Dependency Review
on:
  repository_dispatch:
    types: trigger-ga___dependency-review.yml
permissions:
  contents: read
