env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
jobs:
  report:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: dorny/test-reporter@v1
      with:
        artifact: golang-test-report-${{ matrix.os }}
        name: 'Golang Tests (OS: ${{ matrix.os }})'
        path: '**/*.xml'
        reporter: java-junit
    strategy:
      fail-fast: false
      matrix:
        java:
        - 17
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
name: Go Platform Test Report
on:
  repository_dispatch:
    types: trigger-ga___go-platform-test-report.yml
