env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
jobs:
  report:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: dorny/test-reporter@v1
      with:
        artifact: java-test-report-${{ matrix.os }}-java-${{ matrix.java }}
        name: 'Java Tests (OS: ${{ matrix.os }}, Java: ${{ matrix.java }})'
        path: '**/*.xml'
        reporter: java-junit
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
        - 17
        - 21
        os:
        - windows-latest
name: Java Platform Test Report
on:
  repository_dispatch:
    types: trigger-ga___java-platform-test-report.yml
