env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
jobs:
  build:
    name: Trivy Scan
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        format: sarif
        ignore-unfixed: true
        output: trivy-results.sarif
        scan-type: fs
        severity: CRITICAL
    - continue-on-error: true
      name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy-results.sarif
name: Static Application Security Testing
on:
  repository_dispatch:
    types: trigger-ga___sast.yaml
